[versions]
kotlin = "2.2.21"
ksp = "2.3.3"
kotlinx-serialization = "1.10.0"
buildconfig = "6.0.6"
kotlinpoet = "2.2.0"
shadow = "9.3.0"
dokka = "2.1.0"
publishing-plugin = "0.35.0"
kcp-development = "0.0.1"

[libraries]
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
dokka-plugin = { module = "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }
publishing-plugin = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "publishing-plugin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
publishing = { id = "com.vanniktech.maven.publish", version.ref = "publishing-plugin" }

# KCP-Development plugin aliases
kcp-dev-compiler = { id = "dev.rnett.kcp-development.compiler-plugin", version.ref = "kcp-development" }
kcp-dev-gradle = { id = "dev.rnett.kcp-development.gradle-plugin", version.ref = "kcp-development" }